{% set name = "lemon" %}
{% set version = "1.3.1" %}
{% set sha256 = "71b7c725f4c0b4a8ccb92eb87b208701586cf7a96156ebd821ca3ed855bad3c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://lemon.cs.elte.hu/pub/sources/lemon-{{ version  }}.tar.gz
  sha256: {{ sha256 }}
  patches:
   # NOTE: this disables the installation of the glpk dlls
   # from the lemon build system. An issue has been raised upstream
   # for this:
   # http://lemon.cs.elte.hu/pipermail/lemon-devel/2017-May/000392.html
    - glpk_win.diff    # [win]

build:
  number: 2

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - glpk
    - coincbc       # [unix]
    - doxygen
    - graphviz
    - ghostscript   # [unix]
  run:
    - glpk
    - coincbc       # [unix]

test:
  commands:
    - test -f $PREFIX/include/lemon/glpk.h                 # [unix]
    - test -f $PREFIX/lib/libemon.a                        # [unix]
    - if not exist %LIBRARY_INC%\\lemon\\glpk.h exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\lemon.lib exit 1         # [win]

about:
  home: https://lemon.cs.elte.hu/trac/lemon
  license: Boost-1.0
  license_file: LICENSE
  summary: 'Library for Efficient Modeling and Optimization in Networks'

extra:
  recipe-maintainers:
    - bluescarni
